// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQkQ_mI4zjy2Xnh3ldWr-I5LBX-nXf97Q',
    appId: '1:808438231248:web:e7b2b225b412678aaaeed5',
    messagingSenderId: '808438231248',
    projectId: 'eschool-teacher-2d05c',
    authDomain: 'eschool-teacher-2d05c.firebaseapp.com',
    storageBucket: 'eschool-teacher-2d05c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYjiMNLg7eDbu1WcRmP4B1TCM2jF8aDFA',
    appId: '1:808438231248:android:09346a68aed27da7aaeed5',
    messagingSenderId: '808438231248',
    projectId: 'eschool-teacher-2d05c',
    storageBucket: 'eschool-teacher-2d05c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_ln5SKjR7JuzZf_HJYfo5Gj_JPnmFWE0',
    appId: '1:808438231248:ios:86d455365e277fc5aaeed5',
    messagingSenderId: '808438231248',
    projectId: 'eschool-teacher-2d05c',
    storageBucket: 'eschool-teacher-2d05c.appspot.com',
    iosClientId: '808438231248-ijmgalig73stol8cudiacl04rgg4jo7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.eschoolTeacher',
  );
}
