// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkQKad4ZLQCedJgiVzmKEo_QaRE1hZhzA',
    appId: '1:635164461059:web:386f792fb4511fdb3fa636',
    messagingSenderId: '635164461059',
    projectId: 'school-ff3bf',
    authDomain: 'school-ff3bf.firebaseapp.com',
    storageBucket: 'school-ff3bf.appspot.com',
    measurementId: 'G-VH8FWE20SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCriVXp5kCgFBj0X-HpzFD1EgHR5Y4DMP0',
    appId: '1:635164461059:android:b48b89908caffb313fa636',
    messagingSenderId: '635164461059',
    projectId: 'school-ff3bf',
    storageBucket: 'school-ff3bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACAYuqBxdSHo8m65uFOigX9daYRlh3URk',
    appId: '1:635164461059:ios:199c4bc8ac89590a3fa636',
    messagingSenderId: '635164461059',
    projectId: 'school-ff3bf',
    storageBucket: 'school-ff3bf.appspot.com',
    iosBundleId: 'com.example.eschoolTeacher',
  );
}
